version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ananas-postgres
    restart: always
    environment:
      POSTGRES_USER: ananas_admin
      POSTGRES_PASSWORD: ananas_password_99
      POSTGRES_DB: ananas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ananas-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
